language: go
go:
- '1.12'
sudo: true
branches:
  only:
  - master
services:
  - postgresql
addons:
  postgresql: "9.6"
script:
  - cd AuthService
  - make build
  - cd ..
  - cd FeedbackService
  - make build
  - cd ..
  - cd Gateway
  - make build
  - cd ..
  - cd GtpStorage
  - make build
  - cd ..
  - cd PostService
  - make build
  - cd ..
  - cd ProfileService
  - make build
  - cd ..