version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  auth:
    build: ./AuthService
    restart: always
    depends_on:
      - "db"
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "db"
      DB_NAME: "postgres"
      PRIVATE_KEY: "/etc/keys/private.pem"
      PORT: ":9091"
    volumes:
      - /home/g-tantsevov/keys:/etc/keys
    ports:
      - "9091:9091"
  feedback:
    build: ./FeedbackService
    restart: always
    environment:
      DB_SOURCE: "user=postgres password=postgres dbname=postgres host=db sslmode=disable"
      SMTP_URL: ""
      SMTP_PORT: "423"
      SMTP_LOGIN: ""
      SMTP_PASSWORD: ""
      PORT: ":9092"
    ports:
      - "9092:9092"
  gateway:
    build: ./Gateway
    restart: always
    environment:
      URL_STORAGE: "http://storage:9093"
      URL_AUTH: "auth:9091"
      URL_POST: "http://post:9094"
      URL_PROFILE: "profile:9095"
      PUBLIC_KEY_LOC: "/etc/keys/public.pem"
      PORT: ":9090"
    volumes:
      - /home/g-tantsevov/keys:/etc/keys
    ports:
      - "9090:9090"
  storage:
    build: ./GtpStorage
    restart: always
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "db"
      DB_NAME: "postgres"
      PORT: ":9093"
    ports:
      - "9093:9093"
  post:
    build: ./PostService
    restart: always
    environment:
      DB_SOURCE: "user=postgres password=postgres dbname=postgres host=db sslmode=disable"
      PORT: ":9094"
    ports:
      - "9094:9094"
  profile:
    build: ./ProfileService
    restart: always
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "db"
      DB_NAME: "postgres"
      PORT: ":9095"
    ports:
      - "9095:9095"