// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchString struct {
	Search               string   `protobuf:"bytes,1,opt,name=Search,proto3" json:"Search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchString) Reset()         { *m = SearchString{} }
func (m *SearchString) String() string { return proto.CompactTextString(m) }
func (*SearchString) ProtoMessage()    {}
func (*SearchString) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *SearchString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchString.Unmarshal(m, b)
}
func (m *SearchString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchString.Marshal(b, m, deterministic)
}
func (m *SearchString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchString.Merge(m, src)
}
func (m *SearchString) XXX_Size() int {
	return xxx_messageInfo_SearchString.Size(m)
}
func (m *SearchString) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchString.DiscardUnknown(m)
}

var xxx_messageInfo_SearchString proto.InternalMessageInfo

func (m *SearchString) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type MusicianWithCount struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MusicianWithCount) Reset()         { *m = MusicianWithCount{} }
func (m *MusicianWithCount) String() string { return proto.CompactTextString(m) }
func (*MusicianWithCount) ProtoMessage()    {}
func (*MusicianWithCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{1}
}

func (m *MusicianWithCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MusicianWithCount.Unmarshal(m, b)
}
func (m *MusicianWithCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MusicianWithCount.Marshal(b, m, deterministic)
}
func (m *MusicianWithCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MusicianWithCount.Merge(m, src)
}
func (m *MusicianWithCount) XXX_Size() int {
	return xxx_messageInfo_MusicianWithCount.Size(m)
}
func (m *MusicianWithCount) XXX_DiscardUnknown() {
	xxx_messageInfo_MusicianWithCount.DiscardUnknown(m)
}

var xxx_messageInfo_MusicianWithCount proto.InternalMessageInfo

func (m *MusicianWithCount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MusicianWithCount) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type TabWithSize struct {
	Musician             string   `protobuf:"bytes,1,opt,name=Musician,proto3" json:"Musician,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Size                 float64  `protobuf:"fixed64,3,opt,name=Size,proto3" json:"Size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TabWithSize) Reset()         { *m = TabWithSize{} }
func (m *TabWithSize) String() string { return proto.CompactTextString(m) }
func (*TabWithSize) ProtoMessage()    {}
func (*TabWithSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{2}
}

func (m *TabWithSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TabWithSize.Unmarshal(m, b)
}
func (m *TabWithSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TabWithSize.Marshal(b, m, deterministic)
}
func (m *TabWithSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TabWithSize.Merge(m, src)
}
func (m *TabWithSize) XXX_Size() int {
	return xxx_messageInfo_TabWithSize.Size(m)
}
func (m *TabWithSize) XXX_DiscardUnknown() {
	xxx_messageInfo_TabWithSize.DiscardUnknown(m)
}

var xxx_messageInfo_TabWithSize proto.InternalMessageInfo

func (m *TabWithSize) GetMusician() string {
	if m != nil {
		return m.Musician
	}
	return ""
}

func (m *TabWithSize) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TabWithSize) GetSize() float64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*SearchString)(nil), "protocol.SearchString")
	proto.RegisterType((*MusicianWithCount)(nil), "protocol.MusicianWithCount")
	proto.RegisterType((*TabWithSize)(nil), "protocol.TabWithSize")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0) }

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x03, 0x33, 0x84, 0x38, 0x60, 0x7c, 0x25, 0x35, 0x2e, 0x9e, 0xe0,
	0xd4, 0xc4, 0xa2, 0xe4, 0x8c, 0xe0, 0x92, 0xa2, 0xcc, 0xbc, 0x74, 0x21, 0x31, 0x2e, 0x36, 0x08,
	0x5f, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xca, 0x53, 0xb2, 0xe5, 0x12, 0xf4, 0x2d, 0x2d,
	0xce, 0x4c, 0xce, 0x4c, 0xcc, 0x0b, 0xcf, 0x2c, 0xc9, 0x70, 0xce, 0x2f, 0xcd, 0x2b, 0x11, 0x12,
	0xe2, 0x62, 0xf1, 0x4b, 0xcc, 0x4d, 0x85, 0x2a, 0x05, 0xb3, 0x85, 0x44, 0xb8, 0x58, 0xc1, 0x92,
	0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x10, 0x8e, 0x52, 0x20, 0x17, 0x77, 0x48, 0x62, 0x12,
	0x48, 0x67, 0x70, 0x66, 0x55, 0xaa, 0x90, 0x14, 0x17, 0x07, 0xcc, 0x34, 0xa8, 0x66, 0x38, 0x1f,
	0x6e, 0x28, 0x13, 0x92, 0xa1, 0x42, 0x5c, 0x2c, 0x20, 0x7d, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x8c,
	0x41, 0x60, 0xb6, 0xd1, 0x73, 0x46, 0x2e, 0x96, 0x90, 0xc4, 0xa4, 0x62, 0x21, 0x5f, 0x2e, 0x21,
	0xf7, 0xd4, 0x12, 0xc7, 0xd2, 0x92, 0x8c, 0xfc, 0xa2, 0x62, 0xa7, 0x4a, 0x9f, 0xd4, 0x92, 0x92,
	0xd4, 0x22, 0x21, 0x31, 0x3d, 0xb8, 0x9f, 0x91, 0x3d, 0x28, 0x25, 0x8d, 0x10, 0xc7, 0xf0, 0x90,
	0x12, 0x83, 0x01, 0xa3, 0x90, 0x37, 0x97, 0x00, 0xb2, 0x71, 0x60, 0xfb, 0xc9, 0x36, 0xcc, 0x99,
	0x8b, 0xcf, 0x2d, 0x33, 0x2f, 0x05, 0xe4, 0x4e, 0x02, 0x46, 0x89, 0x22, 0xc4, 0x91, 0x42, 0x0a,
	0x64, 0x48, 0x12, 0x1b, 0x58, 0xc6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xb0, 0xc1, 0xaa,
	0xc6, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TabsClient is the client API for Tabs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TabsClient interface {
	GetAuthorsByLetter(ctx context.Context, in *SearchString, opts ...grpc.CallOption) (Tabs_GetAuthorsByLetterClient, error)
	GetAuthorsByName(ctx context.Context, in *SearchString, opts ...grpc.CallOption) (Tabs_GetAuthorsByNameClient, error)
	FindTabsByName(ctx context.Context, in *SearchString, opts ...grpc.CallOption) (Tabs_FindTabsByNameClient, error)
}

type tabsClient struct {
	cc *grpc.ClientConn
}

func NewTabsClient(cc *grpc.ClientConn) TabsClient {
	return &tabsClient{cc}
}

func (c *tabsClient) GetAuthorsByLetter(ctx context.Context, in *SearchString, opts ...grpc.CallOption) (Tabs_GetAuthorsByLetterClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Tabs_serviceDesc.Streams[0], "/protocol.Tabs/GetAuthorsByLetter", opts...)
	if err != nil {
		return nil, err
	}
	x := &tabsGetAuthorsByLetterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Tabs_GetAuthorsByLetterClient interface {
	Recv() (*MusicianWithCount, error)
	grpc.ClientStream
}

type tabsGetAuthorsByLetterClient struct {
	grpc.ClientStream
}

func (x *tabsGetAuthorsByLetterClient) Recv() (*MusicianWithCount, error) {
	m := new(MusicianWithCount)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tabsClient) GetAuthorsByName(ctx context.Context, in *SearchString, opts ...grpc.CallOption) (Tabs_GetAuthorsByNameClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Tabs_serviceDesc.Streams[1], "/protocol.Tabs/GetAuthorsByName", opts...)
	if err != nil {
		return nil, err
	}
	x := &tabsGetAuthorsByNameClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Tabs_GetAuthorsByNameClient interface {
	Recv() (*MusicianWithCount, error)
	grpc.ClientStream
}

type tabsGetAuthorsByNameClient struct {
	grpc.ClientStream
}

func (x *tabsGetAuthorsByNameClient) Recv() (*MusicianWithCount, error) {
	m := new(MusicianWithCount)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tabsClient) FindTabsByName(ctx context.Context, in *SearchString, opts ...grpc.CallOption) (Tabs_FindTabsByNameClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Tabs_serviceDesc.Streams[2], "/protocol.Tabs/FindTabsByName", opts...)
	if err != nil {
		return nil, err
	}
	x := &tabsFindTabsByNameClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Tabs_FindTabsByNameClient interface {
	Recv() (*TabWithSize, error)
	grpc.ClientStream
}

type tabsFindTabsByNameClient struct {
	grpc.ClientStream
}

func (x *tabsFindTabsByNameClient) Recv() (*TabWithSize, error) {
	m := new(TabWithSize)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TabsServer is the server API for Tabs service.
type TabsServer interface {
	GetAuthorsByLetter(*SearchString, Tabs_GetAuthorsByLetterServer) error
	GetAuthorsByName(*SearchString, Tabs_GetAuthorsByNameServer) error
	FindTabsByName(*SearchString, Tabs_FindTabsByNameServer) error
}

func RegisterTabsServer(s *grpc.Server, srv TabsServer) {
	s.RegisterService(&_Tabs_serviceDesc, srv)
}

func _Tabs_GetAuthorsByLetter_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchString)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TabsServer).GetAuthorsByLetter(m, &tabsGetAuthorsByLetterServer{stream})
}

type Tabs_GetAuthorsByLetterServer interface {
	Send(*MusicianWithCount) error
	grpc.ServerStream
}

type tabsGetAuthorsByLetterServer struct {
	grpc.ServerStream
}

func (x *tabsGetAuthorsByLetterServer) Send(m *MusicianWithCount) error {
	return x.ServerStream.SendMsg(m)
}

func _Tabs_GetAuthorsByName_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchString)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TabsServer).GetAuthorsByName(m, &tabsGetAuthorsByNameServer{stream})
}

type Tabs_GetAuthorsByNameServer interface {
	Send(*MusicianWithCount) error
	grpc.ServerStream
}

type tabsGetAuthorsByNameServer struct {
	grpc.ServerStream
}

func (x *tabsGetAuthorsByNameServer) Send(m *MusicianWithCount) error {
	return x.ServerStream.SendMsg(m)
}

func _Tabs_FindTabsByName_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchString)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TabsServer).FindTabsByName(m, &tabsFindTabsByNameServer{stream})
}

type Tabs_FindTabsByNameServer interface {
	Send(*TabWithSize) error
	grpc.ServerStream
}

type tabsFindTabsByNameServer struct {
	grpc.ServerStream
}

func (x *tabsFindTabsByNameServer) Send(m *TabWithSize) error {
	return x.ServerStream.SendMsg(m)
}

var _Tabs_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Tabs",
	HandlerType: (*TabsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAuthorsByLetter",
			Handler:       _Tabs_GetAuthorsByLetter_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAuthorsByName",
			Handler:       _Tabs_GetAuthorsByName_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FindTabsByName",
			Handler:       _Tabs_FindTabsByName_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protocol.proto",
}
